version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-04-23T00-58-49Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest123
    command: server /data
  adminio-ui:
    image: rzrbld/adminio-ui:release-0.96
    ports:
      - "80:80"
  adminio-api:
    image: rzrbld/adminio-api:release-0.97
    environment:
      MINIO_ACCESS: test
      MINIO_SECRET: testtest123
      MINIO_HOST_PORT: minio:9000
      ADMINIO_HOST_PORT: :8080
    depends_on:
      - minio
      - adminio-ui
    ports:
      - "8080:8080"
